services:
  libreoffice:
    # 指定容器名称
    container_name: libreoffice
    # 指定镜像名称和标签
    image: libreoffice:latest
    # 以守护进程模式运行容器
    restart: always
    # 端口映射，将宿主机的 7005 端口映射到容器的 7005 端口
    ports:
      - "7005:7005"
    # 数据卷挂载，将宿主机的 /opt/libreoffice7.1 目录挂载到容器的 /opt/libreoffice7.1 目录
    volumes:
      - /opt/libreoffice7.1:/opt/libreoffice7.1