name: 部署libreoffice服务

on:
  push:
    branches: [ master ] # 仅当 main 分支有变更时触发
  workflow_dispatch: # 支持手动触发

env:
  DOCKERHUB_REPO: yxy1109/libreoffice  # DockerHub 仓库名

jobs:
#  build-and-push:
#    runs-on: ubuntu-latest
#    steps:
#      - name: 一，获取代码
#        uses: actions/checkout@v4
#
#      - name: 二，登录Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#      - name: 三，生成标签
#        id: tag
#        run: |
#          # 使用提交时间戳作为动态标签（例如 20240615-123456）
#          echo "TAG=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT
#
#      - name: 四，镜像构建和推送
#        uses: docker/build-push-action@v5
#        with:
#          context: .
#          push: true
#          tags: |
#            ${{ env.DOCKERHUB_REPO }}:latest
#            ${{ env.DOCKERHUB_REPO }}:${{ steps.tag.outputs.TAG }}

  deploy:
    runs-on: ubuntu-latest
#    needs: build-and-push  # 依赖构建任务
    steps:
      - name: 一，连接ssh
        # https://github.com/appleboy/ssh-action/blob/master/README.zh-cn.md
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.SSH_KNOWN_HOSTS }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: whoami

      - name: 二，拉取最新镜像并重启服务
        run: |
          pwd
          ls -l
          docker-compose pull      # 拉取最新镜像
          docker-compose up -d --force-recreate     # 重启服务