name: 部署libreoffice服务

on:
  push:
    branches: [ master ] # 仅当 main 分支有变更时触发
  workflow_dispatch: # 支持手动触发

env:
  DOCKERHUB_REPO: yxy1109/libreoffice  # DockerHub 仓库名

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: 一，获取代码
        uses: actions/checkout@v4

      - name: 二，登录Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 三，生成标签
        id: tag
        run: |
          # 使用提交时间戳作为动态标签（例如 20240615-123456）
          echo "TAG=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: 四，镜像构建和推送
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKERHUB_REPO }}:latest
            ${{ env.DOCKERHUB_REPO }}:${{ steps.tag.outputs.TAG }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push  # 依赖构建任务
    steps:
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /path/to/your/project  # 服务器上的项目路径
            docker compose pull      # 拉取最新镜像
            docker compose up -d      # 重启服务